# -*- mode: ruby -*-
# vi: set ft=ruby :

ver = '1.19.6'

Vagrant.configure("2") do |config|
  config.vm.define "nginx" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "nginx-web"
      vb.cpus = 2
      vb.memory = 2048
    end
    cfg.vm.host_name = "nginx"
    cfg.vm.network "private_network", ip: "192.168.122.10"
    cfg.vm.network "forwarded_port", guest: 22, host: 60000, auto_correct: true, id: "ssh"
    cfg.vm.provision "shell",inline: <<-SHELL
      sudo yum -y install net-tools
      sudo yum -y install wget
      sudo wget http://nginx.org/download/nginx-1.19.6.tar.gz
    SHELL


# cfg.vm.provision "shell", path: "config.sh", args: N
# cfg.vm.provision "shell", path: "install_pkg.sh", args: [ Ver, "install_kubectl" ]
# cfg.vm.provision "shell", path: "master_node.sh"
  end
end
