Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

# Create django
  config.vm.define "django" do |django|
    config.vm.hostname = "django"
    config.vm.provider "virtualbox" do |v|
      v.name = 'django'
      v.cpus = 1
      v.memory = 512
    end

# Install Python3.7
    django.vm.provision"shell",inline: <<-SHELL
      sudo yum -y install wget
      sudo yum -y update
      sudo yum install -y gcc openssl-devel bzip2-devel libffi-devel
      cd /usr/src
      sudo wget https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz
      sudo tar xzf Python-3.7.3.tgz
      cd Python-3.7.3
      sudo ./configure --enable-optimizations
      sudo make altinstall
      sudo rm /usr/src/Python-3.7.3.tgz
      sudo yum install -y python3-pip
      sudo pip3 install django
      sudo pip3 install boto3==1.6.19
    SHELL
  end

# Install django
end
